require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/samples", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Sample. As you add validations to Sample, be sure to
  # adjust the attributes here as well.
  let(:sample) { create(:sample) }
  let!(:builded_attributes) { FactoryBot.build(:sample) }

  let(:invalid_attributes) { FactoryBot.build(:sample, codebar: "")}

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SamplesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {  }

  describe "GET /index" do
    it "renders a successful response" do
      get samples_path, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get sample_url(sample), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Sample" do
        expect {
          post samples_url,
               params: { sample: builded_attributes }, headers: valid_headers, as: :json
        }.to change(Sample, :count).by(1)
      end

      it "renders a JSON response with the new sample" do
        post samples_url,
             params: { sample: builded_attributes }, headers: valid_headers, as: :json

        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Sample" do
        expect {
          post samples_url, params: { sample: invalid_attributes }, as: :json
        }.to change(Sample, :count).by(0)
      end

      it "renders a JSON response with errors for the new sample" do
        post samples_url,
             params: { sample: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) { FactoryBot.build(:sample) }

      it "updates the requested sample" do
        patch sample_url(sample),
              params: { sample: new_attributes }, headers: valid_headers, as: :json
        sample.reload
        expect(response.content_type).to match(a_string_including("application/json"))
        expect(response).to have_http_status(:ok)
      end

      it "renders a JSON response with the sample" do
        patch sample_url(sample),
              params: { sample: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the sample" do
        patch sample_url(sample),
              params: { sample: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sample" do
      sample = create(:sample)
      expect {
        delete sample_url(sample), headers: valid_headers, as: :json
      }.to change(Sample, :count).by(-1)
    end
  end
end
